[package]
name = "warren"
version = "0.2.0"
edition = "2024"
repository = "https://github.com/pyrevoid15/warren"
readme = "README.md"
description = """
A data structure similar to plf::hive and boost::container::hub written in Rust. 
Made for fast reuse of space and fast iteration over active entries.
"""

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[profile.test]
opt-level = 3

[dev-dependencies]
rand = "0.10.3"
criterion = "0.8.2"

[dependencies]

[[bench]]
name = "benchy"
harness = false